name: Setup Electron Build Environment
description: Setup Python, uv, Node.js, pnpm with caching for Electron builds

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.11"
  node-version:
    description: Node.js version to use
    required: false
    default: "20"
  pnpm-version:
    description: pnpm version to use
    required: false
    default: "10"
  cache-suffix:
    description: Optional suffix for cache keys (e.g., "x64" for architecture-specific caches)
    required: false
    default: ""

runs:
  using: composite
  steps:
    # Python setup
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # uv installation - Unix
    - name: Install uv (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # uv installation - Windows
    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        irm https://astral.sh/uv/install.ps1 | iex
        echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # pnpm setup
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    # Node.js setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        cache-dependency-path: "frontend/pnpm-lock.yaml"

    # Verify pnpm installation - Unix
    - name: Verify pnpm (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        pnpm --version
        which pnpm

    # Verify pnpm installation - Windows
    - name: Verify pnpm (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        pnpm --version
        echo "pnpm is installed at: $(Get-Command pnpm | Select-Object -ExpandProperty Source)"

    # pnpm cache - Unix
    - name: Get pnpm store directory (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    # pnpm cache - Windows
    - name: Get pnpm store directory (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $env:GITHUB_ENV

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}${{ inputs.cache-suffix && format('-{0}', inputs.cache-suffix) || '' }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}${{ inputs.cache-suffix && format('-{0}', inputs.cache-suffix) || '' }}-pnpm-store-

    # uv cache
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}${{ inputs.cache-suffix && format('-{0}', inputs.cache-suffix) || '' }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}${{ inputs.cache-suffix && format('-{0}', inputs.cache-suffix) || '' }}-uv-
